name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest

      - name: Get version
        id: version
        run: |
          if [ -f version.txt ]; then
            VERSION=$(cat version.txt | tr -d '\n' | tr -d ' ')
            echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "version.txt not found"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

        # App
      - name: Check if App Image version exists
        id: check-app
        run: |
          VERSION=${{ env.VERSION }}
          GHCR_IMAGE=ghcr.io/${{ github.repository }}/next
          GHCR_IMAGE=$(echo $GHCR_IMAGE | tr '[:upper:]' '[:lower:]')

          if docker manifest inspect $GHCR_IMAGE:$VERSION > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push App Image
        if: steps.check-app.outputs.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          target: runner
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/next:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/next:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

        # Migrator
      - name: Check if Migrator Image version exists
        id: check-migrator
        run: |
          VERSION=${{ env.VERSION }}
          GHCR_IMAGE=ghcr.io/${{ github.repository }}/next-migrator
          GHCR_IMAGE=$(echo $GHCR_IMAGE | tr '[:upper:]' '[:lower:]')

          if docker manifest inspect $GHCR_IMAGE:$VERSION > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push Migrator Image
        if: steps.check-migrator.outputs.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          target: builder
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/next-migrator:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/next-migrator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
