name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version
        id: version
        run: |
          if [ -f version.txt ]; then
            VERSION=$(cat version.txt | tr -d '\n' | tr -d ' ')
            echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "version.txt not found"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push App Image
        run: |
          VERSION=${{ env.VERSION }}
          DOCKER_BUILDKIT=1 docker build --target runner -t rullabcd/next:$VERSION .
          docker push rullabcd/next:$VERSION
          docker tag rullabcd/next:$VERSION rullabcd/next:latest
          docker push rullabcd/next:latest

          # GHCR
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/next
          GHCR_IMAGE=$(echo $GHCR_IMAGE | tr '[:upper:]' '[:lower:]')
          docker tag rullabcd/next:$VERSION $GHCR_IMAGE:$VERSION
          docker tag rullabcd/next:$VERSION $GHCR_IMAGE:latest
          docker push $GHCR_IMAGE:$VERSION
          docker push $GHCR_IMAGE:latest

      - name: Build & Push Migrator Image
        run: |
          VERSION=${{ env.VERSION }}
          DOCKER_BUILDKIT=1 docker build --target builder -t rullabcd/next-migrator:$VERSION .
          docker push rullabcd/next-migrator:$VERSION
          docker tag rullabcd/next-migrator:$VERSION rullabcd/next-migrator:latest
          docker push rullabcd/next-migrator:latest

          # GHCR
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/next-migrator
          GHCR_IMAGE=$(echo $GHCR_IMAGE | tr '[:upper:]' '[:lower:]')
          docker tag rullabcd/next-migrator:$VERSION $GHCR_IMAGE:$VERSION
          docker tag rullabcd/next-migrator:$VERSION $GHCR_IMAGE:latest
          docker push $GHCR_IMAGE:$VERSION
          docker push $GHCR_IMAGE:latest
