name: Build & Push Docker Images (GHCR Only)

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version
        id: version
        run: |
          if [ -f version.txt ]; then
            VERSION=$(cat version.txt | tr -d '\n' | tr -d ' ')
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version.txt not found"
            exit 1
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rullabcde
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push App Image
        run: |
          VERSION=${{ env.VERSION }}
          IMAGE_NAME=ghcr.io/rullabcde/next

          docker build --target runner -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Build & Push Migrator Image
        run: |
          VERSION=${{ env.VERSION }}
          IMAGE_NAME=ghcr.io/rullabcde/next-migrator

          docker build --target builder -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
