name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            APP_VERSION=${{ github.event.workflow_run.jobs.docker-build.outputs.version }}

            # Update .env
            if [ -f .env ]; then
              if grep -q "APP_VERSION=" .env; then
                sed -i "s/APP_VERSION=.*/APP_VERSION=$APP_VERSION/" .env
              else
                echo "APP_VERSION=$APP_VERSION" >> .env
              fi
            else
              echo "APP_VERSION=$APP_VERSION" > .env
            fi

            # Login GHCR
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Deploy
            make deploy
            make clean

            echo "Deployment successfully"
