name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: app-version
          path: ./artifact

      - name: Get version for deployment
        id: deploy_version
        run: |
          if [ -f ./artifact/version.txt ]; then
            VERSION=$(cat ./artifact/version.txt | tr -d '\n' | tr -d ' ')
            echo "DEPLOY_VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "DEPLOY_VERSION=latest" >> $GITHUB_ENV
          fi
          echo "REPO_LC=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/letsgo/demo

            # Update .env
            if [ -f .env ]; then
              if grep -q "APP_VERSION=" .env; then
                sed -i "s/APP_VERSION=.*/APP_VERSION=${{ env.DEPLOY_VERSION }}/" .env
              else
                echo "APP_VERSION=${{ env.DEPLOY_VERSION }}" >> .env
              fi
            else
              echo "APP_VERSION=${{ env.DEPLOY_VERSION }}" > .env
            fi

            echo "Deploying version: ${{ env.DEPLOY_VERSION }}"

            # Login GHCR
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Deploy
            make deploy
            make clean

            echo "Deployment successfully"
