name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push App Image
        run: |
          docker build --target runner -t rullabcd/next:${{ env.SHORT_SHA }} .
          docker push rullabcd/next:${{ env.SHORT_SHA }}
          docker tag rullabcd/next:${{ env.SHORT_SHA }} rullabcd/next:latest
          docker push rullabcd/next:latest

      - name: Build & Push Migrator Image
        run: |
          docker build --target builder -t rullabcd/next-migrator:${{ env.SHORT_SHA }} .
          docker push rullabcd/next-migrator:${{ env.SHORT_SHA }}
          docker tag rullabcd/next-migrator:${{ env.SHORT_SHA }} rullabcd/next-migrator:latest
          docker push rullabcd/next-migrator:latest
